version: "3.8"

services:
  ctf-box:
    build: ./
    image: agentzhao/ctf-box:latest
    container_name: ctf-box
    env_file: .env
    volumes:
      - ./workspace:/home/workspace
    ports:
      - 8000:8000
    command: [/bin/zsh]
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
